// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/akashic.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/akashic.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_akashic: GenFile = /*@__PURE__*/
  fileDesc("Ci1kd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2FrYXNoaWMucHJvdG8SH2R3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMihgEKE0FrYXNoaWNNZXNzYWdlRXZlbnQSDAoEdHlwZRgBIAEoCRIOCgZwbGF5SWQYAiABKAkSEQoJaWdub3JhYmxlGAMgASgIEhEKCXRyYW5zaWVudBgEIAEoCBIrCgpwYXJhbWV0ZXJzGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdCL6AQoTQWthc2hpY1N0YXRlUm91dGluZxINCgVlcG9jaBgBIAEoAxJCCgRqb2luGAIgAygLMjQuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcy5Ba2FzaGljTWVzc2FnZUV2ZW50EkoKDGNvbnRpbnVhdGlvbhgDIAMoCzI0LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuQWthc2hpY01lc3NhZ2VFdmVudBJECgZzaGFyZWQYBCADKAsyNC5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkFrYXNoaWNNZXNzYWdlRXZlbnRC1QEKI2NvbS5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zQgxBa2FzaGljUHJvdG9QAaICBUROQ0RBqgIfRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YS5BdG9tc8oCH0R3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGFcQXRvbXPiAitEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21zXEdQQk1ldGFkYXRh6gIjRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YTo6QXRvbXNiBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * @generated from message dwango.nicolive.chat.data.atoms.AkashicMessageEvent
 */
export type AkashicMessageEvent = Message<"dwango.nicolive.chat.data.atoms.AkashicMessageEvent"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string playId = 2;
   */
  playId: string;

  /**
   * @generated from field: bool ignorable = 3;
   */
  ignorable: boolean;

  /**
   * @generated from field: bool transient = 4;
   */
  transient: boolean;

  /**
   * @generated from field: google.protobuf.Struct parameters = 5;
   */
  parameters?: JsonObject;
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.AkashicMessageEvent.
 * Use `create(AkashicMessageEventSchema)` to create a new message.
 */
export const AkashicMessageEventSchema: GenMessage<AkashicMessageEvent> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_akashic, 0);

/**
 * @generated from message dwango.nicolive.chat.data.atoms.AkashicStateRouting
 */
export type AkashicStateRouting = Message<"dwango.nicolive.chat.data.atoms.AkashicStateRouting"> & {
  /**
   * @generated from field: int64 epoch = 1;
   */
  epoch: bigint;

  /**
   * @generated from field: repeated dwango.nicolive.chat.data.atoms.AkashicMessageEvent join = 2;
   */
  join: AkashicMessageEvent[];

  /**
   * @generated from field: repeated dwango.nicolive.chat.data.atoms.AkashicMessageEvent continuation = 3;
   */
  continuation: AkashicMessageEvent[];

  /**
   * @generated from field: repeated dwango.nicolive.chat.data.atoms.AkashicMessageEvent shared = 4;
   */
  shared: AkashicMessageEvent[];
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.AkashicStateRouting.
 * Use `create(AkashicStateRoutingSchema)` to create a new message.
 */
export const AkashicStateRoutingSchema: GenMessage<AkashicStateRouting> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_akashic, 1);

