// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/forwarded.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Chat } from "../atoms_pb";
import { file_dwango_nicolive_chat_data_atoms } from "../atoms_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/forwarded.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_forwarded: GenFile = /*@__PURE__*/
  fileDesc("Ci9kd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2ZvcndhcmRlZC5wcm90bxIfZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcyL7AQoNRm9yd2FyZGVkQ2hhdBItCgRjaGF0GAEgASgLMh8uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5DaGF0EhIKCm1lc3NhZ2VfaWQYAiABKAkSFgoOc291cmNlX2xpdmVfaWQYAyABKAMSSwoEbW9kZRgEIAEoDjI9LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuRm9yd2FyZGVkQ2hhdC5Gb3J3YXJkaW5nTW9kZSJCCg5Gb3J3YXJkaW5nTW9kZRILCgdVTktOT1dOEAASDwoLRlJPTV9DUlVJU0UQARISCg5DT0xMQUJfU0hBUklORxACQtcBCiNjb20uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tc0IORm9yd2FyZGVkUHJvdG9QAaICBUROQ0RBqgIfRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YS5BdG9tc8oCH0R3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGFcQXRvbXPiAitEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21zXEdQQk1ldGFkYXRh6gIjRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YTo6QXRvbXNiBnByb3RvMw", [file_dwango_nicolive_chat_data_atoms]);

/**
 * @generated from message dwango.nicolive.chat.data.atoms.ForwardedChat
 */
export type ForwardedChat = Message<"dwango.nicolive.chat.data.atoms.ForwardedChat"> & {
  /**
   * @generated from field: dwango.nicolive.chat.data.Chat chat = 1;
   */
  chat?: Chat;

  /**
   * @generated from field: string message_id = 2;
   */
  messageId: string;

  /**
   * @generated from field: int64 source_live_id = 3;
   */
  sourceLiveId: bigint;

  /**
   * @generated from field: dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode mode = 4;
   */
  mode: ForwardedChat_ForwardingMode;
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.ForwardedChat.
 * Use `create(ForwardedChatSchema)` to create a new message.
 */
export const ForwardedChatSchema: GenMessage<ForwardedChat> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_forwarded, 0);

/**
 * @generated from enum dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode
 */
export enum ForwardedChat_ForwardingMode {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: FROM_CRUISE = 1;
   */
  FROM_CRUISE = 1,

  /**
   * @generated from enum value: COLLAB_SHARING = 2;
   */
  COLLAB_SHARING = 2,
}

/**
 * Describes the enum dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode.
 */
export const ForwardedChat_ForwardingModeSchema: GenEnum<ForwardedChat_ForwardingMode> = /*@__PURE__*/
  enumDesc(file_dwango_nicolive_chat_data_atoms_forwarded, 0, 0);

