// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/ichibalauncher.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/ichibalauncher.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_ichibalauncher: GenFile = /*@__PURE__*/
  fileDesc("CjRkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL2ljaGliYWxhdW5jaGVyLnByb3RvEh9kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zIo4EChVJY2hpYmFMYXVuY2hlckl0ZW1TZXQSDQoFZXBvY2gYASABKAMSSgoFaXRlbXMYAiADKAsyOy5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkljaGliYUxhdW5jaGVySXRlbVNldC5JdGVtGpkDCgRJdGVtEgoKAmlkGAEgASgJEhAKCGVudGl0eUlkGAIgASgJEhMKC3NlcnZpY2VOYW1lGAMgASgJEg0KBXRpdGxlGAQgASgJEmYKEGxhdW5jaERpYWxvZ1R5cGUYBSABKA4yTC5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkljaGliYUxhdW5jaGVySXRlbVNldC5JdGVtLkxhdW5jaERpYWxvZ1R5cGUSFAoMdGh1bWJuYWlsVXJsGAYgASgJEhYKDnRodW1ibmFpbFdpZHRoGAcgASgFEhcKD3RodW1ibmFpbEhlaWdodBgIIAEoBRIRCglsYXVuY2hVcmwYCSABKAkSGAoLYWRkZWRVc2VySWQYCiABKAlIAIgBARIWCglyZXBvcnRVcmwYCyABKAlIAYgBARIPCgdydW5uaW5nGAwgASgIIiwKEExhdW5jaERpYWxvZ1R5cGUSCQoFU01BTEwQABINCglSSUNISVZJRVcQAUIOCgxfYWRkZWRVc2VySWRCDAoKX3JlcG9ydFVybELcAQojY29tLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXNCE0ljaGliYWxhdW5jaGVyUHJvdG9QAaICBUROQ0RBqgIfRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YS5BdG9tc8oCH0R3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGFcQXRvbXPiAitEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21zXEdQQk1ldGFkYXRh6gIjRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YTo6QXRvbXNiBnByb3RvMw");

/**
 * @generated from message dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet
 */
export type IchibaLauncherItemSet = Message<"dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet"> & {
  /**
   * @generated from field: int64 epoch = 1;
   */
  epoch: bigint;

  /**
   * @generated from field: repeated dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item items = 2;
   */
  items: IchibaLauncherItemSet_Item[];
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.
 * Use `create(IchibaLauncherItemSetSchema)` to create a new message.
 */
export const IchibaLauncherItemSetSchema: GenMessage<IchibaLauncherItemSet> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_ichibalauncher, 0);

/**
 * @generated from message dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item
 */
export type IchibaLauncherItemSet_Item = Message<"dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string entityId = 2;
   */
  entityId: string;

  /**
   * @generated from field: string serviceName = 3;
   */
  serviceName: string;

  /**
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * @generated from field: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType launchDialogType = 5;
   */
  launchDialogType: IchibaLauncherItemSet_Item_LaunchDialogType;

  /**
   * @generated from field: string thumbnailUrl = 6;
   */
  thumbnailUrl: string;

  /**
   * @generated from field: int32 thumbnailWidth = 7;
   */
  thumbnailWidth: number;

  /**
   * @generated from field: int32 thumbnailHeight = 8;
   */
  thumbnailHeight: number;

  /**
   * @generated from field: string launchUrl = 9;
   */
  launchUrl: string;

  /**
   * @generated from field: optional string addedUserId = 10;
   */
  addedUserId?: string;

  /**
   * @generated from field: optional string reportUrl = 11;
   */
  reportUrl?: string;

  /**
   * @generated from field: bool running = 12;
   */
  running: boolean;
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.
 * Use `create(IchibaLauncherItemSet_ItemSchema)` to create a new message.
 */
export const IchibaLauncherItemSet_ItemSchema: GenMessage<IchibaLauncherItemSet_Item> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_ichibalauncher, 0, 0);

/**
 * @generated from enum dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType
 */
export enum IchibaLauncherItemSet_Item_LaunchDialogType {
  /**
   * @generated from enum value: SMALL = 0;
   */
  SMALL = 0,

  /**
   * @generated from enum value: RICHIVIEW = 1;
   */
  RICHIVIEW = 1,
}

/**
 * Describes the enum dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType.
 */
export const IchibaLauncherItemSet_Item_LaunchDialogTypeSchema: GenEnum<IchibaLauncherItemSet_Item_LaunchDialogType> = /*@__PURE__*/
  enumDesc(file_dwango_nicolive_chat_data_atoms_ichibalauncher, 0, 0, 0);

