// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/notifications.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/notifications.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_notifications: GenFile = /*@__PURE__*/
  fileDesc("CjNkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL25vdGlmaWNhdGlvbnMucHJvdG8SH2R3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMi4gIKFFNpbXBsZU5vdGlmaWNhdGlvblYyElQKBHR5cGUYASABKA4yRi5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLlNpbXBsZU5vdGlmaWNhdGlvblYyLk5vdGlmaWNhdGlvblR5cGUSDwoHbWVzc2FnZRgCIAEoCRIVCg1zaG93X2luX3RlbG9wGAMgASgIEhQKDHNob3dfaW5fbGlzdBgEIAEoCCK1AQoQTm90aWZpY2F0aW9uVHlwZRILCgdVTktOT1dOEAASCgoGSUNISUJBEAESCwoHRU1PVElPThACEgoKBkNSVUlTRRADEhQKEFBST0dSQU1fRVhURU5ERUQQBBIOCgpSQU5LSU5HX0lOEAUSCwoHVklTSVRFRBAGEhgKFFNVUFBPUlRFUl9SRUdJU1RFUkVEEAcSEQoNVVNFUl9MRVZFTF9VUBAIEg8KC1VTRVJfRk9MTE9XEAlC2wEKI2NvbS5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zQhJOb3RpZmljYXRpb25zUHJvdG9QAaICBUROQ0RBqgIfRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YS5BdG9tc8oCH0R3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGFcQXRvbXPiAitEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21zXEdQQk1ldGFkYXRh6gIjRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YTo6QXRvbXNiBnByb3RvMw");

/**
 * @generated from message dwango.nicolive.chat.data.atoms.SimpleNotificationV2
 */
export type SimpleNotificationV2 = Message<"dwango.nicolive.chat.data.atoms.SimpleNotificationV2"> & {
  /**
   * @generated from field: dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType type = 1;
   */
  type: SimpleNotificationV2_NotificationType;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: bool show_in_telop = 3;
   */
  showInTelop: boolean;

  /**
   * @generated from field: bool show_in_list = 4;
   */
  showInList: boolean;
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.SimpleNotificationV2.
 * Use `create(SimpleNotificationV2Schema)` to create a new message.
 */
export const SimpleNotificationV2Schema: GenMessage<SimpleNotificationV2> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_notifications, 0);

/**
 * @generated from enum dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType
 */
export enum SimpleNotificationV2_NotificationType {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: ICHIBA = 1;
   */
  ICHIBA = 1,

  /**
   * @generated from enum value: EMOTION = 2;
   */
  EMOTION = 2,

  /**
   * @generated from enum value: CRUISE = 3;
   */
  CRUISE = 3,

  /**
   * @generated from enum value: PROGRAM_EXTENDED = 4;
   */
  PROGRAM_EXTENDED = 4,

  /**
   * @generated from enum value: RANKING_IN = 5;
   */
  RANKING_IN = 5,

  /**
   * @generated from enum value: VISITED = 6;
   */
  VISITED = 6,

  /**
   * @generated from enum value: SUPPORTER_REGISTERED = 7;
   */
  SUPPORTER_REGISTERED = 7,

  /**
   * @generated from enum value: USER_LEVEL_UP = 8;
   */
  USER_LEVEL_UP = 8,

  /**
   * @generated from enum value: USER_FOLLOW = 9;
   */
  USER_FOLLOW = 9,
}

/**
 * Describes the enum dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType.
 */
export const SimpleNotificationV2_NotificationTypeSchema: GenEnum<SimpleNotificationV2_NotificationType> = /*@__PURE__*/
  enumDesc(file_dwango_nicolive_chat_data_atoms_notifications, 0, 0);

