// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/sensitive.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/sensitive.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_sensitive: GenFile = /*@__PURE__*/
  fileDesc("Ci9kd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL3NlbnNpdGl2ZS5wcm90bxIfZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tc0LXAQojY29tLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXNCDlNlbnNpdGl2ZVByb3RvUAGiAgVETkNEQaoCH0R3YW5nby5OaWNvbGl2ZS5DaGF0LkRhdGEuQXRvbXPKAh9Ed2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21z4gIrRHdhbmdvXE5pY29saXZlXENoYXRcRGF0YVxBdG9tc1xHUEJNZXRhZGF0YeoCI0R3YW5nbzo6Tmljb2xpdmU6OkNoYXQ6OkRhdGE6OkF0b21zYgZwcm90bzM");

