// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/atoms/streamstate.proto (package dwango.nicolive.chat.data.atoms, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/atoms/streamstate.proto.
 */
export const file_dwango_nicolive_chat_data_atoms_streamstate: GenFile = /*@__PURE__*/
  fileDesc("CjFkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL3N0cmVhbXN0YXRlLnByb3RvEh9kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zIpQBChFTdHJlYW1TdGF0ZUNoYW5nZRINCgVlcG9jaBgBIAEoAxJHCgVzdGF0ZRgCIAEoDjI4LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuU3RyZWFtU3RhdGVDaGFuZ2UuU3RhdGUiJwoFU3RhdGUSDwoLUEFTU1RIUk9VR0gQABINCglQUk9DRVNTRUQQAULZAQojY29tLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXNCEFN0cmVhbXN0YXRlUHJvdG9QAaICBUROQ0RBqgIfRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YS5BdG9tc8oCH0R3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGFcQXRvbXPiAitEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEF0b21zXEdQQk1ldGFkYXRh6gIjRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YTo6QXRvbXNiBnByb3RvMw");

/**
 * @generated from message dwango.nicolive.chat.data.atoms.StreamStateChange
 */
export type StreamStateChange = Message<"dwango.nicolive.chat.data.atoms.StreamStateChange"> & {
  /**
   * @generated from field: int64 epoch = 1;
   */
  epoch: bigint;

  /**
   * @generated from field: dwango.nicolive.chat.data.atoms.StreamStateChange.State state = 2;
   */
  state: StreamStateChange_State;
};

/**
 * Describes the message dwango.nicolive.chat.data.atoms.StreamStateChange.
 * Use `create(StreamStateChangeSchema)` to create a new message.
 */
export const StreamStateChangeSchema: GenMessage<StreamStateChange> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_atoms_streamstate, 0);

/**
 * @generated from enum dwango.nicolive.chat.data.atoms.StreamStateChange.State
 */
export enum StreamStateChange_State {
  /**
   * @generated from enum value: PASSTHROUGH = 0;
   */
  PASSTHROUGH = 0,

  /**
   * @generated from enum value: PROCESSED = 1;
   */
  PROCESSED = 1,
}

/**
 * Describes the enum dwango.nicolive.chat.data.atoms.StreamStateChange.State.
 */
export const StreamStateChange_StateSchema: GenEnum<StreamStateChange_State> = /*@__PURE__*/
  enumDesc(file_dwango_nicolive_chat_data_atoms_streamstate, 0, 0);

