// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/message.proto (package dwango.nicolive.chat.data, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Chat, GameUpdate, Gift, Nicoad, SimpleNotification, TagUpdated } from "./atoms_pb";
import { file_dwango_nicolive_chat_data_atoms } from "./atoms_pb";
import type { ForwardedChat } from "./atoms/forwarded_pb";
import { file_dwango_nicolive_chat_data_atoms_forwarded } from "./atoms/forwarded_pb";
import type { ModeratorUpdated, SSNGUpdated } from "./atoms/moderator_pb";
import { file_dwango_nicolive_chat_data_atoms_moderator } from "./atoms/moderator_pb";
import type { SimpleNotificationV2 } from "./atoms/notifications_pb";
import { file_dwango_nicolive_chat_data_atoms_notifications } from "./atoms/notifications_pb";
import type { AkashicMessageEvent } from "./atoms/akashic_pb";
import { file_dwango_nicolive_chat_data_atoms_akashic } from "./atoms/akashic_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/message.proto.
 */
export const file_dwango_nicolive_chat_data_message: GenFile = /*@__PURE__*/
  fileDesc("Cidkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL21lc3NhZ2UucHJvdG8SGWR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEi2AYKD05pY29saXZlTWVzc2FnZRIvCgRjaGF0GAEgASgLMh8uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5DaGF0SAASTAoTc2ltcGxlX25vdGlmaWNhdGlvbhgHIAEoCzItLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuU2ltcGxlTm90aWZpY2F0aW9uSAASLwoEZ2lmdBgIIAEoCzIfLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuR2lmdEgAEjMKBm5pY29hZBgJIAEoCzIhLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuTmljb2FkSAASPAoLZ2FtZV91cGRhdGUYDSABKAsyJS5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLkdhbWVVcGRhdGVIABI8Cgt0YWdfdXBkYXRlZBgRIAEoCzIlLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuVGFnVXBkYXRlZEgAEk4KEW1vZGVyYXRvcl91cGRhdGVkGBIgASgLMjEuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcy5Nb2RlcmF0b3JVcGRhdGVkSAASRAoMc3NuZ191cGRhdGVkGBMgASgLMiwuZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcy5TU05HVXBkYXRlZEgAEjoKD292ZXJmbG93ZWRfY2hhdBgUIAEoCzIfLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuQ2hhdEgAEkgKDmZvcndhcmRlZF9jaGF0GBYgASgLMi4uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5hdG9tcy5Gb3J3YXJkZWRDaGF0SAASVwoWc2ltcGxlX25vdGlmaWNhdGlvbl92MhgXIAEoCzI1LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuU2ltcGxlTm90aWZpY2F0aW9uVjJIABJVChVha2FzaGljX21lc3NhZ2VfZXZlbnQYGCABKAsyNC5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zLkFrYXNoaWNNZXNzYWdlRXZlbnRIAEIGCgRkYXRhSgQIAhAHSgQIChANSgQIDhARQrUBCh1jb20uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YUIMTWVzc2FnZVByb3RvUAGiAgRETkNEqgIZRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YcoCGUR3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGHiAiVEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEdQQk1ldGFkYXRh6gIcRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YWIGcHJvdG8z", [file_dwango_nicolive_chat_data_atoms, file_dwango_nicolive_chat_data_atoms_forwarded, file_dwango_nicolive_chat_data_atoms_moderator, file_dwango_nicolive_chat_data_atoms_notifications, file_dwango_nicolive_chat_data_atoms_akashic]);

/**
 * @generated from message dwango.nicolive.chat.data.NicoliveMessage
 */
export type NicoliveMessage = Message<"dwango.nicolive.chat.data.NicoliveMessage"> & {
  /**
   * @generated from oneof dwango.nicolive.chat.data.NicoliveMessage.data
   */
  data: {
    /**
     * @generated from field: dwango.nicolive.chat.data.Chat chat = 1;
     */
    value: Chat;
    case: "chat";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.SimpleNotification simple_notification = 7;
     */
    value: SimpleNotification;
    case: "simpleNotification";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.Gift gift = 8;
     */
    value: Gift;
    case: "gift";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.Nicoad nicoad = 9;
     */
    value: Nicoad;
    case: "nicoad";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.GameUpdate game_update = 13;
     */
    value: GameUpdate;
    case: "gameUpdate";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.TagUpdated tag_updated = 17;
     */
    value: TagUpdated;
    case: "tagUpdated";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.atoms.ModeratorUpdated moderator_updated = 18;
     */
    value: ModeratorUpdated;
    case: "moderatorUpdated";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.atoms.SSNGUpdated ssng_updated = 19;
     */
    value: SSNGUpdated;
    case: "ssngUpdated";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.Chat overflowed_chat = 20;
     */
    value: Chat;
    case: "overflowedChat";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.atoms.ForwardedChat forwarded_chat = 22;
     */
    value: ForwardedChat;
    case: "forwardedChat";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.atoms.SimpleNotificationV2 simple_notification_v2 = 23;
     */
    value: SimpleNotificationV2;
    case: "simpleNotificationV2";
  } | {
    /**
     * @generated from field: dwango.nicolive.chat.data.atoms.AkashicMessageEvent akashic_message_event = 24;
     */
    value: AkashicMessageEvent;
    case: "akashicMessageEvent";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message dwango.nicolive.chat.data.NicoliveMessage.
 * Use `create(NicoliveMessageSchema)` to create a new message.
 */
export const NicoliveMessageSchema: GenMessage<NicoliveMessage> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_message, 0);

