// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file dwango/nicolive/chat/data/origin.proto (package dwango.nicolive.chat.data, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dwango/nicolive/chat/data/origin.proto.
 */
export const file_dwango_nicolive_chat_data_origin: GenFile = /*@__PURE__*/
  fileDesc("CiZkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL29yaWdpbi5wcm90bxIZZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YSJzCg5OaWNvbGl2ZU9yaWdpbhI+CgRjaGF0GAEgASgLMi4uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5OaWNvbGl2ZU9yaWdpbi5DaGF0SAAaFwoEQ2hhdBIPCgdsaXZlX2lkGAEgASgDQggKBm9yaWdpbkK0AQodY29tLmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGFCC09yaWdpblByb3RvUAGiAgRETkNEqgIZRHdhbmdvLk5pY29saXZlLkNoYXQuRGF0YcoCGUR3YW5nb1xOaWNvbGl2ZVxDaGF0XERhdGHiAiVEd2FuZ29cTmljb2xpdmVcQ2hhdFxEYXRhXEdQQk1ldGFkYXRh6gIcRHdhbmdvOjpOaWNvbGl2ZTo6Q2hhdDo6RGF0YWIGcHJvdG8z");

/**
 * @generated from message dwango.nicolive.chat.data.NicoliveOrigin
 */
export type NicoliveOrigin = Message<"dwango.nicolive.chat.data.NicoliveOrigin"> & {
  /**
   * @generated from oneof dwango.nicolive.chat.data.NicoliveOrigin.origin
   */
  origin: {
    /**
     * @generated from field: dwango.nicolive.chat.data.NicoliveOrigin.Chat chat = 1;
     */
    value: NicoliveOrigin_Chat;
    case: "chat";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message dwango.nicolive.chat.data.NicoliveOrigin.
 * Use `create(NicoliveOriginSchema)` to create a new message.
 */
export const NicoliveOriginSchema: GenMessage<NicoliveOrigin> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_origin, 0);

/**
 * @generated from message dwango.nicolive.chat.data.NicoliveOrigin.Chat
 */
export type NicoliveOrigin_Chat = Message<"dwango.nicolive.chat.data.NicoliveOrigin.Chat"> & {
  /**
   * @generated from field: int64 live_id = 1;
   */
  liveId: bigint;
};

/**
 * Describes the message dwango.nicolive.chat.data.NicoliveOrigin.Chat.
 * Use `create(NicoliveOrigin_ChatSchema)` to create a new message.
 */
export const NicoliveOrigin_ChatSchema: GenMessage<NicoliveOrigin_Chat> = /*@__PURE__*/
  messageDesc(file_dwango_nicolive_chat_data_origin, 0, 0);

